# Generated by Django 5.1.6 on 2025-04-26 02:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.SlugField(unique=True, verbose_name="รหัสหมวด")),
                (
                    "display_name",
                    models.CharField(max_length=100, verbose_name="ชื่อหมวด"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="categories/", verbose_name="รูปหมวด"
                    ),
                ),
            ],
            options={
                "verbose_name": "หมวดหมู่อาหาร",
                "verbose_name_plural": "หมวดหมู่อาหาร",
            },
        ),
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="ชื่อดีล")),
                ("image", models.ImageField(upload_to="deals/", verbose_name="รูปดีล")),
                (
                    "original_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="ราคาต้นฉบับ"
                    ),
                ),
                (
                    "discounted_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="ราคาหลังลด"
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="เริ่ม (HH:MM)")),
                ("end_time", models.TimeField(verbose_name="จบ (HH:MM)")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="เปิดใช้งาน"),
                ),
            ],
            options={
                "verbose_name": "ดีล (มื้อเย็น)",
                "verbose_name_plural": "ดีล (มื้อเย็น)",
            },
        ),
        migrations.CreateModel(
            name="FlashMenu",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="ชื่อเมนู")),
                (
                    "image",
                    models.ImageField(upload_to="flash_menus/", verbose_name="รูปเมนู"),
                ),
                (
                    "original_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="ราคาต้นฉบับ"
                    ),
                ),
                (
                    "discounted_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="ราคาหลังลด"
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="เริ่ม (HH:MM)")),
                ("end_time", models.TimeField(verbose_name="จบ (HH:MM)")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="เปิดใช้งาน"),
                ),
            ],
            options={
                "verbose_name": "เมนูนาทีทอง",
                "verbose_name_plural": "เมนูนาทีทอง",
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255, verbose_name="ที่อยู่")),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="ตั้งเป็นค่ามาตรฐาน"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="ชื่อเมนู")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="menus/", verbose_name="รูปเมนู"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="คำอธิบาย")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="ราคา"
                    ),
                ),
                (
                    "favorites",
                    models.ManyToManyField(
                        blank=True,
                        related_name="favorite_menus",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้ที่ชื่นชอบ",
                    ),
                ),
            ],
            options={
                "verbose_name": "เมนู",
                "verbose_name_plural": "เมนู",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="ราคารวม"
                    ),
                ),
                (
                    "placed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="สั่งเมื่อ"
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="ชำระเงินแล้ว"),
                ),
                (
                    "address",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.address",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ออร์เดอร์",
                "verbose_name_plural": "ออร์เดอร์",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="จำนวน"),
                ),
                (
                    "price_at_time",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="ราคาต่อหน่วย"
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.menu",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="myapp.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "สินค้าภายในออร์เดอร์",
                "verbose_name_plural": "สินค้าภายในออร์เดอร์",
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="ชื่อบัตร/บัญชี"),
                ),
                (
                    "details",
                    models.CharField(max_length=255, verbose_name="รายละเอียด"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_address",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="ที่อยู่เริ่มต้น",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="ชื่อร้าน")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="restaurants/", verbose_name="รูปภาพร้าน"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="คำอธิบาย")),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="restaurants",
                        to="myapp.category",
                    ),
                ),
                (
                    "favorites",
                    models.ManyToManyField(
                        blank=True,
                        related_name="favorite_restaurants",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้ที่ชื่นชอบ",
                    ),
                ),
            ],
            options={
                "verbose_name": "ร้านอาหาร",
                "verbose_name_plural": "ร้านอาหาร",
            },
        ),
        migrations.AddField(
            model_name="menu",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menus",
                to="myapp.restaurant",
            ),
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="จำนวน"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.menu"
                    ),
                ),
            ],
            options={
                "verbose_name": "รายการในตะกร้า",
                "verbose_name_plural": "รายการในตะกร้า",
                "unique_together": {("user", "menu")},
            },
        ),
    ]
