# Generated by Django 5.1.6 on 2025-04-27 02:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="details",
            field=models.TextField(blank=True, verbose_name="รายละเอียดเพิ่มเติม"),
        ),
        migrations.AddField(
            model_name="menu",
            name="discount_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="ถ้าไม่ลด ก็ใส่เท่ากับราคาปกติ",
                max_digits=8,
                verbose_name="ราคาหลังลด",
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="end_time",
            field=models.TimeField(
                default=django.utils.timezone.now,
                help_text="เช่น 22:00:00",
                verbose_name="เวลาปิดขาย",
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="start_time",
            field=models.TimeField(
                default=django.utils.timezone.now,
                help_text="เช่น 10:00:00",
                verbose_name="เวลาเริ่มขาย",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="end_time",
            field=models.TimeField(
                default=django.utils.timezone.now, verbose_name="จบ (HH:MM)"
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="start_time",
            field=models.TimeField(
                default=django.utils.timezone.now, verbose_name="เริ่ม (HH:MM)"
            ),
        ),
        migrations.AlterField(
            model_name="flashmenu",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="description",
            field=models.TextField(blank=True, verbose_name="คำอธิบายสั้น"),
        ),
        migrations.AlterField(
            model_name="menu",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="ราคาปกติ"
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menus",
                to="myapp.restaurant",
                verbose_name="ร้านอาหาร",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="FavoriteDeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="เพิ่มเมื่อ"
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="myapp.deal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_deals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ดีลโปรด",
                "verbose_name_plural": "ดีลโปรด",
                "unique_together": {("user", "deal")},
            },
        ),
    ]
