# Generated by Django 5.1.6 on 2025-05-04 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_remove_address_text_address_district_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="myapp.address",
            ),
        ),
    ]
