# Generated by Django 5.1.6 on 2025-05-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_address_order_alter_order_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="wants_sauce",
            field=models.BooleanField(
                default=False, verbose_name="ต้องการซอสหรือเครื่องปรุง"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="wants_spoon",
            field=models.BooleanField(default=False, verbose_name="ต้องการช้อนส้อม"),
        ),
    ]
