# Generated by Django 5.1.6 on 2025-05-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_flashmenu_menu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="menus",
            field=models.ManyToManyField(
                blank=True, to="myapp.menu", verbose_name="เมนูหลัก"
            ),
        ),
    ]
