# Generated by Django 5.1.6 on 2025-05-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0012_order_qr_data_order_slip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="categories/", verbose_name="รูปหมวด"
            ),
        ),
    ]
