# Generated by Django 5.1.6 on 2025-05-11 08:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0014_order_payment_method"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="หัวข้อ")),
                ("content", models.TextField(verbose_name="เนื้อหา")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="community/",
                        verbose_name="รูปภาพ",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="วันที่สร้าง"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="อัปเดตล่าสุด"),
                ),
                (
                    "likes",
                    models.PositiveIntegerField(default=0, verbose_name="ยอดไลก์"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "โพสต์ชุมชน",
                "verbose_name_plural": "โพสต์ชุมชน",
                "ordering": ["-created_at"],
            },
        ),
    ]
