# Generated by Django 5.1.6 on 2025-05-12 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0015_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("display_name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "หมวดหมู่โพสต์",
                "verbose_name_plural": "หมวดหมู่โพสต์",
            },
        ),
        migrations.AddField(
            model_name="post",
            name="feeling",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="ความรู้สึก"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="link",
            field=models.URLField(blank=True, null=True, verbose_name="ลิงก์"),
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.CharField(blank=True, max_length=200, verbose_name="แท็ก"),
        ),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="myapp.postcategory",
                verbose_name="หมวดหมู่",
            ),
        ),
    ]
