# Generated by Django 5.1.6 on 2025-05-12 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0016_postcategory_post_feeling_post_link_post_tags_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="restaurant",
            options={},
        ),
        migrations.AddField(
            model_name="restaurant",
            name="address",
            field=models.CharField(blank=True, max_length=255, verbose_name="ที่อยู่"),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="อีเมล"),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="instagram",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Instagram"
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="line_id",
            field=models.CharField(blank=True, max_length=100, verbose_name="LINE ID"),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="opening_hours",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="เวลาเปิด–ปิด"
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="phone",
            field=models.CharField(blank=True, max_length=50, verbose_name="เบอร์โทร"),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="price_range",
            field=models.CharField(blank=True, max_length=50, verbose_name="ช่วงราคา"),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="rating_avg",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=3,
                null=True,
                verbose_name="คะแนนเฉลี่ย",
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="website",
            field=models.URLField(blank=True, verbose_name="เว็บไซต์"),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myapp.category",
            ),
        ),
    ]
