# Generated by Django 5.1.6 on 2025-05-12 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0017_alter_restaurant_options_restaurant_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="restaurants",
                to="myapp.category",
                verbose_name="หมวดร้าน",
            ),
            preserve_default=False,
        ),
    ]
