# Generated by Django 5.1.6 on 2025-05-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0019_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="community_image",
            field=models.ImageField(
                blank=True,
                upload_to="story/",
                verbose_name="ภาพปกเรื่องราวใน Community",
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="story_full",
            field=models.TextField(blank=True, verbose_name="เรื่องราวเต็ม"),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="story_summary",
            field=models.TextField(blank=True, verbose_name="เรื่องราวแบบย่อ"),
        ),
    ]
