# Generated by Django 5.1.6 on 2025-05-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0020_restaurant_community_image_restaurant_story_full_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="coupon_rewarded",
            field=models.BooleanField(default=False, verbose_name="ได้รับคูปองแล้ว"),
        ),
    ]
