# Generated by Django 5.1.6 on 2025-05-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0009_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_fee",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=6, verbose_name="ค่าจัดส่ง"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="grand_total",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="ยอดสุทธิ"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="ราคารวมสินค้า"
            ),
        ),
    ]
