# Generated by Django 5.1.6 on 2025-05-09 00:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0010_order_delivery_fee_order_grand_total_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="price_at_time",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=8,
                verbose_name="ราคาหลังลดเมื่อเพิ่มลงตะกร้า",
            ),
        ),
    ]
