# Generated by Django 5.1.6 on 2025-05-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0011_cartitem_price_at_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="qr_data",
            field=models.TextField(
                blank=True,
                help_text="สตริงสำหรับสร้าง QR code (PromptPay payload)",
                null=True,
                verbose_name="ข้อมูล QR PromptPay",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="slip",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="payment_slips/",
                verbose_name="สลิปชำระเงิน",
            ),
        ),
    ]
