"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from decouple import config
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+)*o632k8arvw892w#je25(yn6^)nplk^a%pw^&ttptl9!08do'
SECRET_KEY = config('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp',
    'social_django'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # ใช้แทน CommonMiddleware สำหรับ i18n
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',   # <= เติมบรรทัดนี้กลับ
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'myapp' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',     # <— สำคัญ ต้องมี
                'django.template.context_processors.static',
                'social_django.context_processors.backends',  # ← เพิ่มตรงนี้
                'social_django.context_processors.login_redirect',  # ← และตรงนี้
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'th'  # เปลี่ยนเป็น 'th' เพื่อให้แสดงผลเป็นภาษาไทย

LANGUAGES = [
    ('th', 'ไทย'),
    ('en', 'English'),
]

LOCALE_PATHS = [os.path.join(BASE_DIR, 'locale')]

TIME_ZONE = 'Asia/Bangkok'  # เปลี่ยนจาก 'UTC' เป็น 'Asia/Bangkok'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'myapp' / 'static',
]

# === สำหรับการจัดการ media (ไฟล์อัปโหลด เช่น รูปภาพ) ===
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = [
    'social_core.backends.google.GoogleOAuth2',  # ← สำหรับ Google
    'django.contrib.auth.backends.ModelBackend',  # ← Django ปกติ
]
# ค่าที่ได้มาจาก Google API Credentials
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '59553554980-9ig6392raq2m51bkv0i9ij5upa0e2vb9.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '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'
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY    = config('SOCIAL_AUTH_GOOGLE_OAUTH2_KEY')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = config('SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET')



LOGIN_URL = 'social:begin'     # หรือ URL ที่คุณใช้สำหรับหน้า login ของระบบ
LOGIN_REDIRECT_URL = '/'                         # หน้าแรกของคุณหลังล็อกอินเสร็จ
SOCIAL_AUTH_LOGIN_ERROR_URL = '/login-error/'     # (ถ้ามีหน้า error)
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/'              # alias สำหรับ social-auth

SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    'https://www.googleapis.com/auth/userinfo.email',
    'https://www.googleapis.com/auth/userinfo.profile',
]

SOCIAL_AUTH_PIPELINE = [
    'social_core.pipeline.social_auth.social_details',      # ดึงข้อมูลดิบ from Google
    'social_core.pipeline.social_auth.social_uid',          # ตรวจสอบ uid
    'social_core.pipeline.social_auth.auth_allowed',        # เช็คสิทธิ์
    'social_core.pipeline.social_auth.social_user',         # ดูว่ามี SocialUser อยู่แล้วหรือยัง
    'social_core.pipeline.user.get_username',               # สร้าง username เบื้องต้น
    'social_core.pipeline.user.create_user',                # สร้าง User ใหม่ถ้ายังไม่มี
    'social_core.pipeline.social_auth.associate_user',      # ผูก SocialUser กับ User
    'social_core.pipeline.social_auth.load_extra_data',     # เก็บ token/extra_data
    'social_core.pipeline.user.user_details',               # **สำคัญ** ดึง first_name/last_name มาเซ็ตให้
]

ALLOWED_HOSTS = ['localhost', '127.0.0.1']