# Generated by Django 5.1.6 on 2025-04-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_menu_details_menu_discount_price_menu_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="menus",
            field=models.ManyToManyField(blank=True, to="myapp.menu"),
        ),
    ]
