# Generated by Django 5.1.6 on 2025-05-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_deal_menus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="text",
        ),
        migrations.AddField(
            model_name="address",
            name="district",
            field=models.CharField(blank=True, max_length=100, verbose_name="อำเภอ"),
        ),
        migrations.AddField(
            model_name="address",
            name="full_address",
            field=models.TextField(default="", verbose_name="ที่อยู่"),
        ),
        migrations.AddField(
            model_name="address",
            name="label",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="ชื่อที่อยู่"
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="province",
            field=models.CharField(blank=True, max_length=100, verbose_name="จังหวัด"),
        ),
        migrations.AddField(
            model_name="address",
            name="subdistrict",
            field=models.CharField(blank=True, max_length=100, verbose_name="ตำบล"),
        ),
        migrations.AddField(
            model_name="address",
            name="zipcode",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="รหัสไปรษณีย์"
            ),
        ),
    ]
