# Generated by Django 5.1.6 on 2025-05-04 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_order_wants_sauce_order_wants_spoon"),
    ]

    operations = [
        migrations.AddField(
            model_name="flashmenu",
            name="menu",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.menu",
                verbose_name="เมนูหลัก",
            ),
        ),
    ]
