# Generated by Django 5.1.6 on 2025-05-10 00:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0013_alter_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("visa", "VISA"), ("promptpay", "PromptPay")],
                default="visa",
                max_length=20,
                verbose_name="วิธีการชำระเงิน",
            ),
        ),
    ]
